// packages/vue/src/components/AspectRatio.vue
<script setup lang="ts">
import { PHI } from '@renge-ui/tokens';

interface AspectRatioProps {
  ratio?: number;
}

const props = withDefaults(defineProps<AspectRatioProps>(), {
  ratio: PHI,
});

const outerStyle = {
  position: 'relative',
  width: '100%',
  paddingBottom: `${(1 / props.ratio) * 100}%`,
};

const innerStyle = {
  position: 'absolute',
  inset: '0',
  width: '100%',
  height: '100%',
};
</script>

<template>
  <div :style="outerStyle" v-bind="$attrs">
    <div :style="innerStyle">
      <slot />
    </div>
  </div>
</template>

// packages/svelte/src/components/AspectRatio.svelte
<script lang="ts">
  import { PHI } from '@renge-ui/tokens';

  export let ratio: number = PHI;
  export let style = '';

  const paddingBottom = `${(1 / ratio) * 100}%`;

  const outerStyle = `position: relative; width: 100%; padding-bottom: ${paddingBottom};`;
  const innerStyle = `position: absolute; inset: 0; width: 100%; height: 100%;`;
</script>

<div style="{outerStyle} {style}" {...$$restProps}>
  <div style={innerStyle}>
    <slot />
  </div>
</div>
