// packages/vue/src/components/Avatar.vue
<script setup lang="ts">
interface AvatarProps {
  src?: string;
  alt?: string;
  initials?: string;
  size?: '1' | '2' | '3' | '4' | '5';
  shape?: 'circle' | 'square';
}

const props = withDefaults(defineProps<AvatarProps>(), {
  size: '3',
  shape: 'circle',
});

const sizePx = {
  '1': 20,
  '2': 32,
  '3': 52,
  '4': 84,
  '5': 136,
};

const fontSizeFor = {
  '1': 'var(--renge-font-size-xs)',
  '2': 'var(--renge-font-size-sm)',
  '3': 'var(--renge-font-size-base)',
  '4': 'var(--renge-font-size-lg)',
  '5': 'var(--renge-font-size-xl)',
};

const px = sizePx[props.size];
const radius = props.shape === 'circle' ? 'var(--renge-radius-full)' : 'var(--renge-radius-3)';
const label = props.initials ? props.initials.slice(0, 2).toUpperCase() : undefined;

const avatarStyle = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  width: `${px}px`,
  height: `${px}px`,
  borderRadius: radius,
  overflow: 'hidden',
  flexShrink: 0,
  background: props.src ? undefined : 'var(--renge-color-bg-muted)',
  color: 'var(--renge-color-fg-inverse)',
  fontSize: fontSizeFor[props.size],
  fontWeight: 600,
  userSelect: 'none',
};

const imgStyle = {
  width: '100%',
  height: '100%',
  objectFit: 'cover',
  display: 'block',
};
</script>

<template>
  <div :style="avatarStyle" :aria-label="alt" :role="alt ? 'img' : undefined" v-bind="$attrs">
    <img v-if="src" :src="src" :alt="alt ?? ''" :style="imgStyle" />
    <span v-else>{{ label }}</span>
  </div>
</template>

// packages/svelte/src/components/Avatar.svelte
<script lang="ts">
  export let src: string | undefined = undefined;
  export let alt: string | undefined = undefined;
  export let initials: string | undefined = undefined;
  export let size: '1' | '2' | '3' | '4' | '5' = '3';
  export let shape: 'circle' | 'square' = 'circle';
  export let style = '';

  const sizePx = {
    '1': 20,
    '2': 32,
    '3': 52,
    '4': 84,
    '5': 136,
  };

  const fontSizeFor = {
    '1': 'var(--renge-font-size-xs)',
    '2': 'var(--renge-font-size-sm)',
    '3': 'var(--renge-font-size-base)',
    '4': 'var(--renge-font-size-lg)',
    '5': 'var(--renge-font-size-xl)',
  };

  const px = sizePx[size];
  const radius = shape === 'circle' ? 'var(--renge-radius-full)' : 'var(--renge-radius-3)';
  const label = initials ? initials.slice(0, 2).toUpperCase() : undefined;

  const baseStyles = `
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: ${px}px;
    height: ${px}px;
    border-radius: ${radius};
    overflow: hidden;
    flex-shrink: 0;
    background: ${src ? 'none' : 'var(--renge-color-bg-muted)'};
    color: var(--renge-color-fg-inverse);
    font-size: ${fontSizeFor[size]};
    font-weight: 600;
    user-select: none;
  `;

  const imgStyle = 'width: 100%; height: 100%; object-fit: cover; display: block;';
</script>

<div
  aria-label={alt}
  role={alt ? 'img' : undefined}
  style="{baseStyles} {style}"
  {...$$restProps}
>
  {#if src}
    <img {src} alt={alt ?? ''} style={imgStyle} />
  {:else}
    {label}
  {/if}
</div>
