// packages/vue/src/components/Grid.vue
<script setup lang="ts">
interface GridProps {
  columns?: number | string;
  rows?: number | string;
  gap?: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  gapX?: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  gapY?: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  align?: 'start' | 'center' | 'end' | 'stretch';
  justify?: 'start' | 'center' | 'end' | 'stretch';
}

const props = withDefaults(defineProps<GridProps>(), {
  columns: 1,
  gap: '3',
  align: 'stretch',
  justify: 'stretch',
});

const getTemplate = (value: number | string | undefined) => {
  if (value === undefined) return undefined;
  if (typeof value === 'number') return `repeat(${value}, 1fr)`;
  return value;
};

const gridStyle = {
  display: 'grid',
  gridTemplateColumns: getTemplate(props.columns),
  gridTemplateRows: getTemplate(props.rows),
  columnGap: props.gapX ? `var(--renge-space-${props.gapX})` : `var(--renge-space-${props.gap})`,
  rowGap: props.gapY ? `var(--renge-space-${props.gapY})` : `var(--renge-space-${props.gap})`,
  alignItems: props.align,
  justifyItems: props.justify,
};
</script>

<template>
  <div :style="gridStyle" v-bind="$attrs">
    <slot />
  </div>
</template>

// packages/svelte/src/components/Grid.svelte
<script lang="ts">
  export let columns: number | string = 1;
  export let rows: number | string | undefined = undefined;
  export let gap: '0' | '1' | '2' | '3' | '4' | '5' | '6' = '3';
  export let gapX: '0' | '1' | '2' | '3' | '4' | '5' | '6' | undefined = undefined;
  export let gapY: '0' | '1' | '2' | '3' | '4' | '5' | '6' | undefined = undefined;
  export let align: 'start' | 'center' | 'end' | 'stretch' = 'stretch';
  export let justify: 'start' | 'center' | 'end' | 'stretch' = 'stretch';
  export let style = '';

  const getTemplate = (value: number | string | undefined) => {
    if (value === undefined) return undefined;
    if (typeof value === 'number') return `repeat(${value}, 1fr)`;
    return value;
  };

  const columnGap = gapX ? `var(--renge-space-${gapX})` : `var(--renge-space-${gap})`;
  const rowGap = gapY ? `var(--renge-space-${gapY})` : `var(--renge-space-${gap})`;

  const baseStyles = `
    display: grid;
    grid-template-columns: ${getTemplate(columns) || ''};
    ${getTemplate(rows) ? `grid-template-rows: ${getTemplate(rows)};` : ''}
    column-gap: ${columnGap};
    row-gap: ${rowGap};
    align-items: ${align};
    justify-items: ${justify};
  `;
</script>

<div style="{baseStyles} {style}" {...$$restProps}>
  <slot />
</div>
