// packages/vue/src/components/ModalFooter.vue
<script setup lang="ts">
</script>

<template>
  <div
    :style="{
      padding: 'var(--renge-space-5)',
      borderTop: '1px solid var(--renge-color-border-subtle)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 'var(--renge-space-3)',
    }"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/components/ModalFooter.svelte
<script lang="ts">
  let className = '';
  export { className as class };
</script>

<div
  class={className}
  style="
    padding: var(--renge-space-5);
    border-top: 1px solid var(--renge-color-border-subtle);
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: var(--renge-space-3);
  "
  {...$$restProps}
>
  <slot />
</div>
