// packages/vue/src/components/Navbar.vue
<script setup lang="ts">
export type SpaceKey = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8'

export interface NavbarProps {
  sticky?: boolean
  border?: boolean
  height?: string
  paddingX?: SpaceKey
}

withDefaults(defineProps<NavbarProps>(), {
  sticky: false,
  border: true,
  height: '56px',
  paddingX: '5',
})
</script>

<template>
  <nav
    :style="{
      display: 'flex',
      alignItems: 'center',
      minHeight: height,
      padding: `0 var(--renge-space-${paddingX})`,
      background: 'var(--renge-color-bg)',
      borderBottom: border ? '1px solid var(--renge-color-border-subtle)' : undefined,
      position: sticky ? 'sticky' : undefined,
      top: sticky ? 0 : undefined,
      zIndex: sticky ? 100 : undefined,
      boxSizing: 'border-box',
    }"
    v-bind="$attrs"
  >
    <slot />
  </nav>
</template>

// packages/svelte/src/components/Navbar.svelte
<script lang="ts">
  type SpaceKey = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8';

  export let sticky: boolean = false;
  export let border: boolean = true;
  export let height: string = '56px';
  export let paddingX: SpaceKey = '5';
  let className = '';
  export { className as class };

  let navElement: HTMLElement;

  const baseStyles = `
    display: flex;
    align-items: center;
    min-height: ${height};
    padding: 0 var(--renge-space-${paddingX});
    background: var(--renge-color-bg);
    border-bottom: ${border ? '1px solid var(--renge-color-border-subtle)' : 'none'};
    position: ${sticky ? 'sticky' : 'relative'};
    top: ${sticky ? '0' : 'auto'};
    z-index: ${sticky ? '100' : 'auto'};
    box-sizing: border-box;
  `;
</script>

<nav
  bind:this={navElement}
  class={className}
  style={baseStyles}
  {...$$restProps}
>
  <slot />
</nav>
