// packages/vue/src/components/RengeProvider.vue
<script setup lang="ts">
import { useRengeTheme } from "../composables/useRengeTheme";
import { onMounted } from "vue";

interface Props {
  profile?: string;
  mode?: "light" | "dark";
}

const props = withDefaults(defineProps<Props>(), {
  profile: "ocean",
  mode: "light",
});

const { switchProfile, switchMode } = useRengeTheme();

onMounted(() => {
  switchProfile(props.profile);
  switchMode(props.mode);
});
</script>

<template>
  <slot />
</template>

<style scoped>
/* RengeProvider is a wrapper component that applies theme context */
</style>

// packages/svelte/src/components/RengeProvider.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { switchProfile, switchMode } from "../stores/theme";

  export let profile: string = "ocean";
  export let mode: "light" | "dark" = "light";

  onMount(() => {
    switchProfile(profile);
    switchMode(mode);
  });
</script>

<slot />

<style>
  /* RengeProvider is a wrapper component that applies theme context */
</style>
