// packages/vue/src/components/TabPanel.vue
<script setup lang="ts">
import { inject, computed } from 'vue'

export interface TabPanelProps {
  value: string
}

const props = defineProps<TabPanelProps>()

const ctx = inject<any>('tabs', null)
const isActive = computed(() => ctx?.active === props.value)
</script>

<template>
  <div
    v-if="isActive"
    role="tabpanel"
    :id="`tabpanel-${value}`"
    :aria-labelledby="`tab-${value}`"
    :style="{
      paddingTop: 'var(--renge-space-4)',
    }"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/components/TabPanel.svelte
<script lang="ts">
  import { getContext } from 'svelte';

  export let value: string;
  let className = '';
  export { className as class };

  const ctx = getContext<any>('tabs') || { activeTab: { subscribe: () => {} } };
  let isActive = false;

  ctx.activeTab.subscribe((v: string) => {
    isActive = v === value;
  });
</script>

{#if isActive}
  <div
    role="tabpanel"
    id="tabpanel-{value}"
    aria-labelledby="tab-{value}"
    class={className}
    style="padding-top: var(--renge-space-4);"
    {...$$restProps}
  >
    <slot />
  </div>
{/if}
