// packages/svelte/src/components/Accordion.svelte
<script lang="ts">
  import { setContext } from 'svelte';
  import { writable, type Writable } from 'svelte/store';

  export let multiple: boolean = false;
  export let value: string | string[] | undefined = undefined;

  let className = '';
  export { className as class };

  const openIds: Writable<Set<string>> = writable(
    new Set(Array.isArray(value) ? value : value ? [value] : [])
  );

  function toggle(id: string) {
    openIds.update((ids) => {
      const newIds = new Set(ids);
      if (newIds.has(id)) {
        newIds.delete(id);
      } else {
        if (!multiple) {
          newIds.clear();
        }
        newIds.add(id);
      }
      return newIds;
    });
  }

  setContext('accordion', { openIds, toggle });
</script>

<div class={className} style="border: 1px solid var(--renge-color-border-subtle); border-radius: var(--renge-radius-2);" {...$$restProps}>
  <slot />
</div>

// packages/vue/src/components/Accordion.vue
<script setup lang="ts">
import { ref, provide } from 'vue'

export interface AccordionProps {
  multiple?: boolean
  value?: string | string[]
}

const props = withDefaults(defineProps<AccordionProps>(), {
  multiple: false,
})

const openIds = ref<Set<string>>(
  new Set(Array.isArray(props.value) ? props.value : props.value ? [props.value] : [])
)

function toggle(id: string) {
  const newIds = new Set(openIds.value)
  if (newIds.has(id)) {
    newIds.delete(id)
  } else {
    if (!props.multiple) {
      newIds.clear()
    }
    newIds.add(id)
  }
  openIds.value = newIds
}

provide('accordion', { openIds, toggle })
</script>

<template>
  <div
    :style="{
      border: '1px solid var(--renge-color-border-subtle)',
      borderRadius: 'var(--renge-radius-2)',
    }"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>
