// packages/svelte/src/components/ButtonGroupItem.svelte
<script lang="ts">
  export let position: 'first' | 'middle' | 'last' | 'only' = 'only';
  export let orientation: 'horizontal' | 'vertical' = 'horizontal';
  export let radius: 'none' | '1' | '2' | '3' | 'full' = '2';
  let className = '';
  export { className as class };
</script>

<div style="display: contents" {...$$restProps}>
  <slot />
</div>

// packages/vue/src/components/ButtonGroupItem.vue
<script setup lang="ts">
export interface ButtonGroupItemProps {
  position?: 'first' | 'middle' | 'last' | 'only'
  orientation?: 'horizontal' | 'vertical'
  radius?: 'none' | '1' | '2' | '3' | 'full'
}

withDefaults(defineProps<ButtonGroupItemProps>(), {
  position: 'only',
  orientation: 'horizontal',
  radius: '2',
})
</script>

<template>
  <div :style="{ display: 'contents' }" v-bind="$attrs">
    <slot />
  </div>
</template>
