// packages/svelte/src/components/Divider.svelte
<script lang="ts">
  export let orientation: 'horizontal' | 'vertical' = 'horizontal';
  export let spacing: '0' | '1' | '2' | '3' | '4' | '5' | '6' = '3';
  export let color: 'border' | 'border-subtle' = 'border-subtle';
  export let style = '';

  const isHorizontal = orientation === 'horizontal';

  const baseStyles = `
    border: none;
    background-color: var(--renge-color-${color});
    ${isHorizontal
      ? `
        height: 1px;
        width: 100%;
        margin-block: var(--renge-space-${spacing});
      `
      : `
        width: 1px;
        height: 100%;
        margin-inline: var(--renge-space-${spacing});
      `}
  `;
</script>

<hr style="{baseStyles} {style}" {...$$restProps} />

// packages/vue/src/components/Divider.vue
<script setup lang="ts">
interface DividerProps {
  orientation?: 'horizontal' | 'vertical';
  spacing?: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  color?: 'border' | 'border-subtle';
}

const props = withDefaults(defineProps<DividerProps>(), {
  orientation: 'horizontal',
  spacing: '3',
  color: 'border-subtle',
});

const isHorizontal = props.orientation === 'horizontal';

const dividerStyle = {
  border: 'none',
  backgroundColor: `var(--renge-color-${props.color})`,
  ...(isHorizontal
    ? {
        height: '1px',
        width: '100%',
        marginBlock: `var(--renge-space-${props.spacing})`,
      }
    : {
        width: '1px',
        height: '100%',
        marginInline: `var(--renge-space-${props.spacing})`,
      }),
};
</script>

<template>
  <hr :style="dividerStyle" v-bind="$attrs" />
</template>
