// packages/svelte/src/components/KBD.svelte
<script lang="ts">
  export let keys: string[] = [];
  export let style = '';

  let keyList = keys;

  const containerStyle = 'display: inline-flex; align-items: center; gap: 4px; font-family: monospace;';
  const keyStyle = 'display: inline-block; min-width: 24px; height: 24px; line-height: 24px; text-align: center; background: var(--renge-color-bg-subtle); border: 1px solid var(--renge-color-border); border-radius: var(--renge-radius-1); padding: 0 var(--renge-space-1); font-size: var(--renge-font-size-xs); font-weight: 600;';
  const separatorStyle = 'margin: 0 4px;';
</script>

<kbd style="{containerStyle} {style}" {...$$restProps}>
  {#each keyList as key, idx}
    <span>
      {#if idx > 0}
        <span style={separatorStyle}>+</span>
      {/if}
      <span style={keyStyle}>
        {key.trim()}
      </span>
    </span>
  {/each}
</kbd>

// packages/vue/src/components/KBD.vue
<script setup lang="ts">
interface KBDProps {
  keys?: string[];
}

const props = withDefaults(defineProps<KBDProps>(), {
  keys: () => [],
});

const kbdStyle = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: '4px',
  fontFamily: 'monospace',
};

const keyStyle = {
  display: 'inline-block',
  minWidth: '24px',
  height: '24px',
  lineHeight: '24px',
  textAlign: 'center',
  background: 'var(--renge-color-bg-subtle)',
  border: '1px solid var(--renge-color-border)',
  borderRadius: 'var(--renge-radius-1)',
  padding: '0 var(--renge-space-1)',
  fontSize: 'var(--renge-font-size-xs)',
  fontWeight: 600,
};

const separatorStyle = {
  margin: '0 4px',
};
</script>

<template>
  <kbd :style="kbdStyle" v-bind="$attrs">
    <span v-for="(key, idx) in keys" :key="idx">
      <span v-if="idx > 0" :style="separatorStyle">+</span>
      <span :style="keyStyle">{{ key.trim() }}</span>
    </span>
  </kbd>
</template>
