// packages/svelte/src/components/ModalHeader.svelte
<script lang="ts">
  let className = '';
  export { className as class };
</script>

<div
  class={className}
  style="
    padding: var(--renge-space-5);
    border-bottom: 1px solid var(--renge-color-border-subtle);
    display: flex;
    align-items: center;
    justify-content: space-between;
  "
  {...$$restProps}
>
  <slot />
</div>

// packages/vue/src/components/ModalHeader.vue
<script setup lang="ts">
</script>

<template>
  <div
    :style="{
      padding: 'var(--renge-space-5)',
      borderBottom: '1px solid var(--renge-color-border-subtle)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
    }"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>
