// packages/svelte/src/components/ModalBody.svelte
<script lang="ts">
  let className = '';
  export { className as class };
</script>

<div
  class={className}
  style="
    padding: var(--renge-space-5);
    color: var(--renge-color-fg);
    font-size: var(--renge-font-size-base);
    line-height: var(--renge-line-height-relaxed);
  "
  {...$$restProps}
>
  <slot />
</div>

// packages/vue/src/components/ModalBody.vue
<script setup lang="ts">
</script>

<template>
  <div
    :style="{
      padding: 'var(--renge-space-5)',
      color: 'var(--renge-color-fg)',
      fontSize: 'var(--renge-font-size-base)',
      lineHeight: 'var(--renge-line-height-relaxed)',
    }"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>
