// packages/react/src/components/Slider.tsx
// packages/react/src/components/Slider.tsx
//
// Range slider. The track uses a Fibonacci-height strip. Optional phi markers
// show the natural subdivision points (0.382 and 0.618) — the golden section.
// PHI markers divide the range at exactly the golden ratio from both ends.

import { forwardRef, type ComponentPropsWithoutRef } from 'react';

// Inject thumb/track styles once (can't do ::-webkit-slider-thumb in inline styles)
if (typeof document !== 'undefined') {
  const id = '__renge-slider-styles__';
  if (!document.getElementById(id)) {
    const s = document.createElement('style');
    s.id = id;
    s.textContent = `
.renge-slider {
  -webkit-appearance: none;
  appearance: none;
  width: 100%;
  cursor: pointer;
  background: transparent;
  outline: none;
}
.renge-slider::-webkit-slider-runnable-track {
  height: 4px;
  background: var(--renge-color-border);
  border-radius: var(--renge-radius-full);
}
.renge-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 18px;
  height: 18px;
  margin-top: -7px;
  border-radius: var(--renge-radius-full);
  background: var(--renge-color-accent);
  border: 2px solid var(--renge-color-bg);
  box-shadow: 0 1px 4px rgba(0,0,0,0.2);
  transition: box-shadow var(--renge-duration-1) var(--renge-easing-ease-out);
}
.renge-slider::-webkit-slider-thumb:hover {
  box-shadow: 0 0 0 4px var(--renge-color-accent-subtle);
}
.renge-slider::-moz-range-track {
  height: 4px;
  background: var(--renge-color-border);
  border-radius: var(--renge-radius-full);
}
.renge-slider::-moz-range-thumb {
  width: 18px;
  height: 18px;
  border-radius: var(--renge-radius-full);
  background: var(--renge-color-accent);
  border: 2px solid var(--renge-color-bg);
  box-shadow: 0 1px 4px rgba(0,0,0,0.2);
  cursor: pointer;
}
.renge-slider:focus-visible::-webkit-slider-thumb {
  box-shadow: 0 0 0 3px var(--renge-color-border-focus);
}
@media (hover: none) and (pointer: coarse) {
  .renge-slider::-webkit-slider-thumb {
    width: 28px;
    height: 28px;
    margin-top: -12px;
  }
  .renge-slider::-moz-range-thumb {
    width: 28px;
    height: 28px;
  }
}`;
    document.head.appendChild(s);
  }
}

export interface SliderProps extends Omit<ComponentPropsWithoutRef<'input'>, 'type'> {
  /** Show golden ratio marker lines at 0.382 and 0.618 of the range */
  showPhiMarkers?: boolean;
  label?: string;
  showValue?: boolean;
}

export const Slider = forwardRef<HTMLInputElement, SliderProps>(
  function Slider({ showPhiMarkers = false, label, showValue = false, style, min = 0, max = 100, value, defaultValue, ...props }, ref) {
    const numMin = Number(min);
    const numMax = Number(max);
    const numVal = value !== undefined ? Number(value) : defaultValue !== undefined ? Number(defaultValue) : numMin;

    // Golden section points: 0.382 (1 - 1/φ) and 0.618 (1/φ)
    const phi382 = numMin + (numMax - numMin) * 0.382;
    const phi618 = numMin + (numMax - numMin) * 0.618;

    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--renge-space-2)', ...style }}>
        {(label || showValue) && (
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            {label && (
              <span style={{ fontSize: 'var(--renge-font-size-sm)', color: 'var(--renge-color-fg-subtle)' }}>
                {label}
              </span>
            )}
            {showValue && (
              <span style={{ fontSize: 'var(--renge-font-size-sm)', color: 'var(--renge-color-accent)', fontVariantNumeric: 'tabular-nums' }}>
                {numVal}
              </span>
            )}
          </div>
        )}
        <div style={{ position: 'relative' }}>
          <input
            ref={ref}
            type="range"
            className="renge-slider"
            min={min}
            max={max}
            value={value}
            defaultValue={defaultValue}
            {...props}
          />
          {/* PHI markers */}
          {showPhiMarkers && (
            <div style={{ position: 'relative', marginTop: 'var(--renge-space-1)', height: 8, pointerEvents: 'none' }}>
              {[phi382, phi618].map((point) => {
                const pct = ((point - numMin) / (numMax - numMin)) * 100;
                return (
                  <div
                    key={point}
                    style={{
                      position: 'absolute',
                      left: `${pct}%`,
                      top: 0,
                      transform: 'translateX(-50%)',
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'center',
                      gap: 2,
                    }}
                  >
                    <div style={{ width: 1, height: 6, background: 'var(--renge-color-accent)', opacity: 0.5 }} />
                    <span style={{ fontSize: '9px', color: 'var(--renge-color-fg-muted)', lineHeight: 1 }}>
                      {point === phi382 ? 'φ⁻¹' : 'φ⁻²'}
                    </span>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    );
  }
);

// packages/vue/src/components/Slider.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'

export interface SliderProps {
  modelValue?: number
  min?: number
  max?: number
  step?: number
  showPhiMarkers?: boolean
  label?: string
  showValue?: boolean
  disabled?: boolean
}

const props = withDefaults(defineProps<SliderProps>(), {
  modelValue: 0,
  min: 0,
  max: 100,
  step: 1,
  showPhiMarkers: false,
  showValue: false,
  disabled: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: number]
  change: [event: Event]
  input: [event: Event]
}>()

const numMin = computed(() => Number(props.min))
const numMax = computed(() => Number(props.max))
const numVal = computed(() =>
  props.modelValue !== undefined ? Number(props.modelValue) : numMin.value
)

const phi382 = computed(() => numMin.value + (numMax.value - numMin.value) * 0.382)
const phi618 = computed(() => numMin.value + (numMax.value - numMin.value) * 0.618)

const phiMarkers = computed(() => [
  { point: phi382.value, label: 'φ⁻¹' },
  { point: phi618.value, label: 'φ⁻²' },
])

const markerStyle = (point: number) => ({
  position: 'absolute',
  left: `${((point - numMin.value) / (numMax.value - numMin.value)) * 100}%`,
  top: 0,
  transform: 'translateX(-50%)',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  gap: '2px',
})

const markerLine = {
  width: '1px',
  height: '6px',
  background: 'var(--renge-color-accent)',
  opacity: 0.5,
}

const markerLabel = {
  fontSize: '9px',
  color: 'var(--renge-color-fg-muted)',
  lineHeight: 1,
}

const wrapperStyle = computed(() => ({
  display: 'flex',
  flexDirection: 'column',
  gap: 'var(--renge-space-2)',
}))

const labelRowStyle = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
}

const labelStyle = {
  fontSize: 'var(--renge-font-size-sm)',
  color: 'var(--renge-color-fg-subtle)',
}

const valueStyle = {
  fontSize: 'var(--renge-font-size-sm)',
  color: 'var(--renge-color-accent)',
  fontVariantNumeric: 'tabular-nums',
}

const sliderContainerStyle = {
  position: 'relative',
}

const handleChange = (e: Event) => {
  const target = e.currentTarget as HTMLInputElement
  emit('update:modelValue', Number(target.value))
  emit('change', e)
}

const handleInput = (e: Event) => {
  const target = e.currentTarget as HTMLInputElement
  emit('update:modelValue', Number(target.value))
  emit('input', e)
}

onMounted(() => {
  if (typeof document !== 'undefined') {
    const id = '__renge-slider-styles__'
    if (!document.getElementById(id)) {
      const s = document.createElement('style')
      s.id = id
      s.textContent = `
.renge-slider {
  -webkit-appearance: none;
  appearance: none;
  width: 100%;
  cursor: pointer;
  background: transparent;
  outline: none;
}
.renge-slider::-webkit-slider-runnable-track {
  height: 4px;
  background: var(--renge-color-border);
  border-radius: var(--renge-radius-full);
}
.renge-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 18px;
  height: 18px;
  margin-top: -7px;
  border-radius: var(--renge-radius-full);
  background: var(--renge-color-accent);
  border: 2px solid var(--renge-color-bg);
  box-shadow: 0 1px 4px rgba(0,0,0,0.2);
  transition: box-shadow var(--renge-duration-1) var(--renge-easing-ease-out);
}
.renge-slider::-webkit-slider-thumb:hover {
  box-shadow: 0 0 0 4px var(--renge-color-accent-subtle);
}
.renge-slider::-moz-range-track {
  height: 4px;
  background: var(--renge-color-border);
  border-radius: var(--renge-radius-full);
}
.renge-slider::-moz-range-thumb {
  width: 18px;
  height: 18px;
  border-radius: var(--renge-radius-full);
  background: var(--renge-color-accent);
  border: 2px solid var(--renge-color-bg);
  box-shadow: 0 1px 4px rgba(0,0,0,0.2);
  cursor: pointer;
}
.renge-slider:focus-visible::-webkit-slider-thumb {
  box-shadow: 0 0 0 3px var(--renge-color-border-focus);
}
@media (hover: none) and (pointer: coarse) {
  .renge-slider::-webkit-slider-thumb {
    width: 28px;
    height: 28px;
    margin-top: -12px;
  }
  .renge-slider::-moz-range-thumb {
    width: 28px;
    height: 28px;
  }
}`
      document.head.appendChild(s)
    }
  }
})
</script>

<template>
  <div :style="wrapperStyle" v-bind="$attrs">
    <div v-if="label || showValue" :style="labelRowStyle">
      <span v-if="label" :style="labelStyle">
        {{ label }}
      </span>
      <span v-if="showValue" :style="valueStyle">
        {{ numVal }}
      </span>
    </div>
    <div :style="sliderContainerStyle">
      <input
        type="range"
        class="renge-slider"
        :min="min"
        :max="max"
        :step="step"
        :value="modelValue"
        :disabled="disabled"
        @change="handleChange"
        @input="handleInput"
      />
      <div
        v-if="showPhiMarkers"
        style="
          position: relative;
          margin-top: var(--renge-space-1);
          height: 8px;
          pointer-events: none;
        "
      >
        <div
          v-for="marker in phiMarkers"
          :key="marker.point"
          :style="markerStyle(marker.point)"
        >
          <div :style="markerLine" />
          <span :style="markerLabel">
            {{ marker.label }}
          </span>
        </div>
      </div>
    </div>
  </div>
</template>
