// packages/svelte/src/components/TableRow.svelte
<script lang="ts">
  export let index: number | undefined = undefined;
  let className = '';
  export { className as class };

  let rowElement: HTMLTableRowElement;

  const isEven = index !== undefined && index % 2 === 1;
</script>

<tr
  bind:this={rowElement}
  class={className}
  style="
    background: {isEven ? 'var(--renge-color-bg-subtle)' : 'transparent'};
    border-bottom: 1px solid var(--renge-color-border-subtle);
    transition: background var(--renge-duration-1) var(--renge-easing-ease-out);
  "
  {...$$restProps}
>
  <slot />
</tr>

// packages/vue/src/components/TableRow.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface TableRowProps {
  index?: number
}

const props = defineProps<TableRowProps>()

const isEven = computed(() => props.index !== undefined && props.index % 2 === 1)
</script>

<template>
  <tr
    :style="{
      background: isEven ? 'var(--renge-color-bg-subtle)' : 'transparent',
      borderBottom: '1px solid var(--renge-color-border-subtle)',
      transition: 'background var(--renge-duration-1) var(--renge-easing-ease-out)',
    }"
    v-bind="$attrs"
  >
    <slot />
  </tr>
</template>
