// packages/svelte/src/components/TableCell.svelte
<script lang="ts">
  export let muted: boolean = false;
  let className = '';
  export { className as class };

  let cellElement: HTMLTableCellElement;
</script>

<td
  bind:this={cellElement}
  class={className}
  style="
    padding: var(--renge-space-3) var(--renge-space-4);
    color: {muted ? 'var(--renge-color-fg-muted)' : 'var(--renge-color-fg)'};
    font-size: var(--renge-font-size-base);
    vertical-align: middle;
  "
  {...$$restProps}
>
  <slot />
</td>

// packages/vue/src/components/TableCell.vue
<script setup lang="ts">
export interface TableCellProps {
  muted?: boolean
}

withDefaults(defineProps<TableCellProps>(), {
  muted: false,
})
</script>

<template>
  <td
    :style="{
      padding: 'var(--renge-space-3) var(--renge-space-4)',
      color: muted ? 'var(--renge-color-fg-muted)' : 'var(--renge-color-fg)',
      fontSize: 'var(--renge-font-size-base)',
      verticalAlign: 'middle',
    }"
    v-bind="$attrs"
  >
    <slot />
  </td>
</template>
