// packages/svelte/src/components/Tabs.svelte
<script lang="ts">
  import { createEventDispatcher, setContext, getContext } from 'svelte';
  import { writable, type Writable } from 'svelte/store';

  export let defaultTab: string = '';
  export let value: string | undefined = undefined;
  export let onChange: ((id: string) => void) | undefined = undefined;

  let className = '';
  export { className as class };

  const activeTab: Writable<string> = writable(value ?? defaultTab);
  const setActive = (id: string) => {
    const isControlled = value !== undefined;
    if (!isControlled) {
      activeTab.set(id);
    }
    onChange?.(id);
  };

  setContext('tabs', { activeTab, setActive });

  let tabsElement: HTMLDivElement;

  $: if (value !== undefined) {
    activeTab.set(value);
  }
</script>

<div
  bind:this={tabsElement}
  class={className}
  style="display: flex; flex-direction: column;"
  {...$$restProps}
>
  <slot />
</div>

// packages/vue/src/components/Tabs.vue
<script setup lang="ts">
import { ref, provide, watch } from 'vue'

export interface TabsProps {
  defaultTab?: string
  value?: string
  onChange?: (id: string) => void
}

const props = withDefaults(defineProps<TabsProps>(), {
  defaultTab: '',
})

const internalActive = ref(props.defaultTab)

const isControlled = props.value !== undefined
const active = isControlled ? props.value! : internalActive.value

const setActive = (id: string) => {
  if (!isControlled) internalActive.value = id
  props.onChange?.(id)
}

watch(
  () => props.value,
  (val) => {
    if (val !== undefined) internalActive.value = val
  }
)

provide('tabs', { active, setActive })
</script>

<template>
  <div :style="{ display: 'flex', flexDirection: 'column' }" v-bind="$attrs">
    <slot />
  </div>
</template>
