// packages/react/src/components/VisuallyHidden.tsx
import { forwardRef } from 'react';
import type { ComponentPropsWithoutRef } from 'react';

export interface VisuallyHiddenProps extends ComponentPropsWithoutRef<'span'> {}

export const VisuallyHidden = forwardRef<HTMLSpanElement, VisuallyHiddenProps>(
  (props, ref) => (
    <span
      ref={ref}
      style={{
        position: 'absolute',
        width: '1px',
        height: '1px',
        padding: 0,
        margin: '-1px',
        overflow: 'hidden',
        clip: 'rect(0, 0, 0, 0)',
        whiteSpace: 'nowrap',
        borderWidth: 0,
      }}
      {...props}
    />
  )
);

VisuallyHidden.displayName = 'VisuallyHidden';

// packages/vue/src/components/VisuallyHidden.vue
<script setup lang="ts">
interface VisuallyHiddenProps {}

defineProps<VisuallyHiddenProps>();

const style = {
  position: 'absolute',
  width: '1px',
  height: '1px',
  padding: 0,
  margin: '-1px',
  overflow: 'hidden',
  clip: 'rect(0, 0, 0, 0)',
  whiteSpace: 'nowrap',
  borderWidth: 0,
};
</script>

<template>
  <span :style="style" v-bind="$attrs">
    <slot />
  </span>
</template>
